export const skillDescriptions = {
  javascript: [
    '// Core',
    'const expertise = [',
    '  "ES6+",',
    '  "TypeScript",',
    '  "Async/Await",',
    '  "Promises"',
    '];',
    '// Runtime',
    'const runtime = [',
    '  "Node.js",',
    '  "Browser APIs",',
    '  "Web Workers"',
    '];',
    '// Tools',
    'const tools = [',
    '  "npm/yarn",',
    '  "Webpack",',
    '  "Babel"',
    '];'
  ],
  react: [
    '// Core',
    'const core = [',
    '  "React 18",',
    '  "Redux Toolkit",',
    '  "React Query"',
    '];',
    '// Architecture',
    'const architecture = [',
    '  "Next.js 14",',
    '  "Server Components",',
    '  "TypeScript"',
    '];',
    '// Performance',
    'const performance = [',
    '  "Code Splitting",',
    '  "Lazy Loading",',
    '  "Memoization"',
    '];'
  ],
  nodejs: [
    '// Backend',
    'const backend = [',
    '  "Express",',
    '  "REST APIs",',
    '  "WebSocket"',
    '];',
    '// Integration',
    'const integration = [',
    '  "MongoDB",',
    '  "AWS Services",',
    '  "BLE Devices"',
    '];',
    '// Security',
    'const security = [',
    '  "JWT",',
    '  "OAuth",',
    '  "Encryption"',
    '];'
  ],
  mongodb: [
    '// Core',
    'const core = [',
    '  "CRUD Ops",',
    '  "Aggregation",',
    '  "Indexing"',
    '];',
    '// Advanced',
    'const advanced = [',
    '  "Atlas",',
    '  "Mongoose",',
    '  "Transactions"',
    '];',
    '// Performance',
    'const performance = [',
    '  "Optimization",',
    '  "Sharding",',
    '  "Caching"',
    '];'
  ],
  express: [
    '// Core',
    'const core = [',
    '  "Middleware",',
    '  "Routing",',
    '  "Controllers"',
    '];',
    '// Features',
    'const features = [',
    '  "Auth System",',
    '  "File Upload",',
    '  "Error Handling"',
    '];',
    '// Integration',
    'const integration = [',
    '  "MongoDB",',
    '  "Redis Cache",',
    '  "Cloud Storage"',
    '];'
  ],
  aws: [
    '// Core',
    'const core = [',
    '  "EC2",',
    '  "S3",',
    '  "Lambda"',
    '];',
    '// Healthcare',
    'const healthcare = [',
    '  "HIPAA Compliance",',
    '  "Data Security",',
    '  "Backup Systems"',
    '];',
    '// DevOps',
    'const devops = [',
    '  "CI/CD",',
    '  "CloudWatch",',
    '  "IAM"',
    '];'
  ],
  html5: [
    '// Modern',
    'const modern = [',
    '  "Semantic Tags",',
    '  "Web Components",',
    '  "Canvas"',
    '];',
    '// APIs',
    'const apis = [',
    '  "Web Storage",',
    '  "WebSocket",',
    '  "Geolocation"',
    '];',
    '// Integration',
    'const integration = [',
    '  "SVG",',
    '  "Media",',
    '  "Forms"',
    '];'
  ],
  css3: [
    '// Layout',
    'const layout = [',
    '  "Flexbox",',
    '  "Grid",',
    '  "Responsive"',
    '];',
    '// Modern',
    'const modern = [',
    '  "Tailwind",',
    '  "Animations",',
    '  "Variables"',
    '];',
    '// Tools',
    'const tools = [',
    '  "Sass",',
    '  "PostCSS",',
    '  "Modules"',
    '];'
  ],
  git: [
    '// Core',
    'const core = [',
    '  "Version Control",',
    '  "Branching",',
    '  "Merging"',
    '];',
    '// CI/CD',
    'const cicd = [',
    '  "GitHub Actions",',
    '  "Automated Tests",',
    '  "Deployments"',
    '];',
    '// Collaboration',
    'const collaboration = [',
    '  "Code Review",',
    '  "Pull Requests",',
    '  "Documentation"',
    '];'
  ],
  jest: [
    '// Testing',
    'const testing = [',
    '  "Unit Tests",',
    '  "Integration",',
    '  "E2E"',
    '];',
    '// Features',
    'const features = [',
    '  "Mock Data",',
    '  "API Testing",',
    '  "Coverage"',
    '];',
    '// Tools',
    'const tools = [',
    '  "React Testing",',
    '  "Snapshot Tests",',
    '  "CI Integration"',
    '];'
  ],
  blockchain: [
    '// DeFi',
    'const defi = [',
    '  "Web3.js",',
    '];',
    '// Trading',
    'const trading = [',
    '  "Algorithmic",',
    '  "Portfolio Systems",',
    '  "Market Analysis"',
    '];',
    '// Tools',
    'const tools = [',
    '  "MetaMask",',
    '  "Ethers.js",',
    '];'
  ],
  reactnative: [
    '// Core',
    'const core = [',
    '  "Navigation",',
    '  "State Management",',
    '  "Native Modules"',
    '];',
    '// Features',
    'const features = [',
    '  "BLE Integration",',
    '  "Push Notifications",',
    '  "Offline Storage"',
    '];',
    '// Performance',
    'const performance = [',
    '  "Memory Profiling",',
    '  "Native Bridge",',
    '  "Optimization"',
    '];'
  ],
  python: [
    '// Analysis',
    'const analysis = [',
    '  "Data Processing",',
    '  "Visualization",',
    '  "Statistics"',
    '];',
    '// Healthcare',
    'const healthcare = [',
    '  "Signal Processing",',
    '  "Medical Data",',
    '  "Research Tools"',
    '];'
  ],
  devops: [
    '// CI/CD',
    'const cicd = [',
    '  "Jenkins",',
    '];',
  ]
};