export const skillDescriptions = {
  javascript: [
    '// Core',
    'const expertise = [',
    '  "ES6+",',
    '  "Async & Functional Programming",',
    '',
    '];',
    '// Frameworks',
    'const frameworks = [',
    '  "React",',
    '  "Vue",',
    '  "Angular"',
    '];',
    '// Advanced',
    'const concepts = [',
    '  "Closures",',
    '  "Prototypes",',
    '  "Memory Management"',
    '];',
    '// Tools',
    'const tools = [',
    '  "Webpack",',
    '  "Babel",',
    '  "ESLint"',
    '];'
  ],
  react: [
    '// Components',
    'const components = [',
    '  "Functional",',
    '  "Class",',
    '  "HOCs"',
    '];',
    '// State',
    'const stateManagement = [',
    '  "Redux",',
    '  "Context API",',
    '  "MobX"',
    '];',
    '// Hooks',
    'const hooks = [',
    '  "useState",',
    '  "useEffect",',
    '  "useContext",',
    '  "useReducer",',
    '  "Custom"',
    '];',
    '// Optimization',
    'const optimization = [',
    '  "React.memo",',
    '  "useMemo",',
    '  "useCallback",',
    '  "Code Splitting"',
    '];'
  ],
  nodejs: [
    '// Server-Side',
    'const serverSide = [',
    '  "RESTful APIs",',
    '  "GraphQL",',
    '  "Microservices"',
    '];',
    '// Databases',
    'const databases = [',
    '  "MongoDB",',
    '  "PostgreSQL",',
    '  "Redis"',
    '];',
    '// Security',
    'const security = [',
    '  "JWT",',
    '  "OAuth",',
    '  "Helmet.js",',
    '  "Rate Limiting"',
    '];',
    '// Performance',
    'const performance = [',
    '  "Clustering",',
    '  "Load Balancing",',
    '  "Caching"',
    '];'
  ],
  mongodb: [
    '// Modeling',
    'const dataModeling = [',
    '  "Schema Design",',
    '  "Normalization",',
    '  "Denormalization"',
    '];',
    '// Operations',
    'const operations = [',
    '  "Complex Queries",',
    '  "Aggregation",',
    '  "Text Search"',
    '];',
    '// Tuning',
    'const tuning = [',
    '  "Query Optimization",',
    '  "Indexing",',
    '  "Caching"',
    '];',
    '// Admin',
    'const admin = [',
    '  "Replication",',
    '  "Sharding",',
    '  "Backup/Restore"',
    '];'
  ],
  express: [
    '// Routing',
    'const routing = [',
    '  "Route Params",',
    '  "Query Strings",',
    '  "Middleware"',
    '];',
    '// API',
    'const api = [',
    '  "RESTful Practices",',
    '  "Versioning",',
    '  "Rate Limiting"',
    '];',
    '// Errors',
    'const errorHandling = [',
    '  "Global Handler",',
    '  "Custom Errors",',
    '  "Async Errors"',
    '];',
    '// Integration',
    'const integration = [',
    '  "ORMs",',
    '  "Auth Strategies",',
    '  "Third-party APIs"',
    '];'
  ],
  aws: [
    '// Compute',
    'const compute = [',
    '  "EC2",',
    '  "Lambda",',
    '  "ECS"',
    '];',
    '// Storage',
    'const storage = [',
    '  "S3",',
    '  "EBS",',
    '  "RDS"',
    '];',
    '// Network',
    'const networking = [',
    '  "VPC",',
    '  "Route 53",',
    '  "CloudFront"',
    '];',
    '// DevOps',
    'const devops = [',
    '  "CloudFormation",',
    '  "CodePipeline",',
    '  "Elastic Beanstalk"',
    '];'
  ],
  html5: [
    '// Semantic',
    'const semantics = [',
    '  "Header",',
    '  "Nav",',
    '  "Article",',
    '  "Section",',
    '  "Aside",',
    '  "Footer"',
    '];',
    '// Media',
    'const multimedia = [',
    '  "Audio",',
    '  "Video",',
    '  "Canvas"',
    '];',
    '// Forms',
    'const forms = [',
    '  "Input Types",',
    '  "Validation",',
    '  "Custom Controls"',
    '];',
    '// APIs',
    'const apis = [',
    '  "Geolocation",',
    '  "Web Storage",',
    '  "Service Workers"',
    '];'
  ],
  css3: [
    '// Layout',
    'const layout = [',
    '  "Flexbox",',
    '  "Grid",',
    '  "Multi-column"',
    '];',
    '// Responsive',
    'const responsive = [',
    '  "Media Queries",',
    '  "Fluid Typography",',
    '  "Mobile-First"',
    '];',
    '// Animation',
    'const animations = [',
    '  "Keyframes",',
    '  "Transitions",',
    '  "Transform"',
    '];',
    '// Modern',
    'const modern = [',
    '  "Custom Properties",',
    '  "Calc()",',
    '  "CSS Modules"',
    '];'
  ],
  git: [
    '// Version Control',
    'const versionControl = [',
    '  "Branching",',
    '  "Merging",',
    '  "Rebasing"',
    '];',
    '// Collaboration',
    'const collaboration = [',
    '  "Pull Requests",',
    '  "Code Reviews",',
    '  "Issue Tracking"',
    '];',
    '// Advanced',
    'const advanced = [',
    '  "Interactive",',
    '  "Submodules"',
    '];',
    '// CI/CD',
    'const cicd = [',
    '  "Git Hooks",',
    '  "GitHub Actions",',
    '  "GitLab CI"',
    '];'
  ],
  jest: [
    '// Test Types',
    'const testTypes = [',
    '  "Unit",',
    '  "Integration",',
    '  "Snapshot"',
    '];',
    '// Mocking',
    'const mocking = [',
    '  "Function Mocks",',
    '  "Module Mocks",',
    '  "Timer Mocks"',
    '];',
    '// Async',
    'const asyncTesting = [',
    '  "Promises",',
    '  "Async/Await",',
    '  "Callbacks"',
    '];',
    '// Coverage',
    'const coverage = [',
    '  "Statement",',
    '  "Branch",',
    '  "Function"',
    '];'
  ]
};